name       : libtxc_dxtn
version    : 1.0.1
release    : 1
source     :
    - http://people.freedesktop.org/~cbrill/libtxc_dxtn/libtxc_dxtn-1.0.1.tar.bz2 : 45290d12cdca529a3f41e7fc35c4250fc1b6d2fc16b56680f8401f6aa792ae60
license    : MIT
summary    : S3TC with DRI drivers
description: |
    S3TC with DRI drivers
builddeps  :
    - pkgconfig32(gl)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
libsplit   : no
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf ${installdir}/usr/include
    %make clean
