name       : libtxc_dxtn
version    : 1.1
release    : 4
source     :
    - git|https://github.com/divVerent/s2tc.git : f6ec862d7594e29ae80a6e49f66ad4c76cf09abc
license    : MIT
summary    : S3TC with DRI drivers
component  : desktop.library
description: |
    S2TC with DRI drivers
builddeps  :
    - pkgconfig32(gl)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
libsplit   : no
setup      : |
    %autogen --prefix=/usr \
             --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
